### ISSUE TITLE
feat: implement new SearchSources

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#120]
# Feature Request

**Describe the Feature Request**

Additional SearchSources should be implemented (see #106 for an overview).

**Describe Preferred Solution**

The ERIC database would be a good starting point because it is similar to the Crossref API, which is already supported (see [crossref SearchSource](https://github.com/geritwagner/colrev/blob/main/colrev/ops/built_in/search_sources/crossref.py)). In fact, the code skeleton for the [ERIC SearchSource](https://github.com/geritwagner/colrev/blob/main/colrev/ops/built_in/search_sources/eric.py) already exists. To support API-based searches, the run_search(...) method needs to be implemented (parsing the json response from ERIC). To add a new ERIC-API-based search (and the search parameters), the add_endpoint method needs to be extended.

The [arXiv API](https://info.arxiv.org/help/api/) provides a different format (xml). The code for the [pubmed SearchSource](https://github.com/CoLRev-Ecosystem/colrev/blob/main/colrev/ops/built_in/search_sources/pubmed.py) provides a good starting point for parsing xml content.

The IEEXplore database is a more challenging example because it requires a registration (an API key). You need to apply for it before you can access the API. The implementation of run_search(...) in the corresponding code skeleton is similar to the ERIC case. The only difference is that the API key must be stored in a local settings file (as a secret). To create a local settings file, code for the [project settings](https://github.com/geritwagner/colrev/blob/main/colrev/settings.py) (especially the load_settings() and save_settings()) would be useful. The settings should be handled by the environment_manager and available through the review_manager.

**Expected Effort Required**

2 months,  5 people.

**Comment by Cohen2000** [comment]
Hi, Ich hätte Lust dieses Issue zu bearbeiten :)

**Comment by MalouSchmidt** [comment]
Ich bin dabei!

**Comment by RheaDoesStuff** [comment]
Ich wäre auch daran interessiert an diesem Issue mitzuarbeiten :)

**Comment by Lexi04** [comment]
Hallo, ich hätte auch Interesse mitzuarbeiten!

**Comment by AntonFrisch** [comment]
Hallo, ich wäre auch an dem Thema interessiert.

**Comment by frxdericz** [comment]
Ich auch🤚

**Comment by geritwagner** [comment]
@frxdericz: die Nachmeldung ist ausnahmsweise ok, da die Gruppe noch nicht voll war.

**Comment by RheaDoesStuff** [comment]
Hallo ihr Lieben, 

hat für den Milestone schon ein Treffen stattgefunden? 
Falls nicht, wollen wir uns vielleicht mal zusammen setzen? :)

**Comment by Cohen2000** [comment]
> Hallo ihr Lieben,
> 
> hat für den Milestone schon ein Treffen stattgefunden? Falls nicht, wollen wir uns vielleicht mal zusammen setzen? :)

Hi,
Wir sind bis jetzt eine 3er Gruppe und haben auch schon eine WhatsApp Gruppe. Du kannst mir gerne hier oder unter 'albert-vincent.borchardt@stud.uni-bamberg.de' deine Handynummer schreiben, dann kann ich dich hinzufügen :)

**Comment by Janus678** [comment]
@Cohen2000 
Hallo zusammen,
wie seid ihr in der Gruppe :) 
Kann ich noch anschließen ?

**Comment by Cohen2000** [comment]
> @Cohen2000 Hallo zusammen, wie seid ihr in der Gruppe :) Kann ich noch anschließen ?

Hi, stand jetzt sind wir zu viert, heißt wir haben noch einen Platz frei. Du kannst mir auch gerne unter 'albert-vincent.borchardt@stud.uni-bamberg.de' deine Handynummer schreiben, dann kann ich dich noch hinzufügen :)

**Comment by Janus678** [comment]
@Cohen2000 vielen Dank :) habe dir gerade ne Mail geschrieben!

**Comment by geritwagner** [comment]
FYI: #187 recently introduced changes relevant to the local settings.

**Comment by geritwagner** [comment]
A quick update on ERIC: there is a `publicationtype` field that could be used to set the `ENTRYTYPE`.

**Comment by Janus678** [comment]
@geritwagner können sich bitte nochmal assignen :) ich hatte mich gerade vertippt 
Vielen Dank. ☺️
