### ISSUE TITLE
feat: add journals to local_index

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#129]
# Feature Request

**Describe the Feature Request**

Journal names and rankings should be added to the [local_index](https://github.com/CoLRev-Ecosystem/colrev/blob/main/colrev/env/local_index.py), which makes data available to the different CoLRev operations efficiently. In particular, journal rankings should be added in the prep operation and be available for automated prescreen exclusion.

Example rankings:
- [Senior Scholars' List of Premier Journals](https://aisnet.org/page/SeniorScholarListofPremierJournals)
- [VHB-JOURQUAL3 Ranking](https://vhbonline.org/vhb4you/vhb-jourqual/vhb-jourqual-3/gesamtliste)
- [FT-50](https://www.ft.com/content/3405a512-5cbb-11e1-8f1f-00144feabdc0)
- [Beall's list of predatory journals](https://github.com/CoLRev-Ecosystem/colrev/blob/main/colrev/template/ops/predatory_journals_beall.csv)

**Describe Preferred Solution**

An appropriate data structure for storing journals and journal rankings in the SQLite database should be determined. The table(s) should be created and filled upon index creation (`colrev env -i`). The code for inserting data into SQLite could resemble the [__add_index_records](https://github.com/CoLRev-Ecosystem/colrev/blob/main/colrev/env/local_index.py).

In the prep operation, journal ranking information should be added to the records, for example by introducing a new field:
```
  journal_ranking      = {Senior Scholars' List of Premier Journals; FT50; VHB-JOURQUAL3 A+},
```
It should be easy to use journal rankings for automated prescreening decisions.

Finally, an integration with the [CoLRev curated journals](https://github.com/CoLRev-curations) and the [colrev curation data endpoint](https://github.com/CoLRev-Ecosystem/colrev/blob/main/colrev/ops/built_in/data/colrev_curation.py) (see [example](https://github.com/CoLRev-curations/mis-quarterly/blob/main/settings.json)) may be helpful.

**Expected Effort Required**

2 months, 5 people.

**Comment by Janus678** [comment]
Ich bin interessiert an diesem Issue! Option 1

**Comment by mhlbrsimon** [comment]
Hallo, dieses Thema würde ich im Rahmen des WI-Projekts alternativ bearbeiten.

**Comment by Lexi04** [comment]
Hallo, ich hätte an dem Thema Interesse.

**Comment by AntonFrisch** [comment]
Hallo, ich wäre ebenfalls an dem Thema interessiert.
