### ISSUE TITLE
feat: add a review project dashboard

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#130]
# Feature Request

**Describe the Feature Request**

A colrev extension should provide a dashboard with an overview of the project and displaying a profile of the sample.

**Describe Preferred Solution**

As a starting point, tutorials on Python dashboards, including plotly and dash would be useful (e.g., [1](https://www.statworx.com/en/content-hub/blog/how-to-build-a-dashboard-in-python-plotly-dash-step-by-step-tutorial/), [2](https://realpython.com/python-dash/), or [3](https://medium.com/innovation-res/how-to-build-an-app-using-dash-plotly-and-python-and-deploy-it-to-aws-5d8d2c7bd652)).

As a first step, the sample of papers (all records with colrev_status=rev_synthesized) should be displayed in a table, allowing users to explore the dataset by sorting, filtering, and searching for records.

Next, the profile of the sample should be visualized. Typical visualizations include the profile of papers published over time, or the most frequent publication outlets (journals).

Finally, a burn-down chart should be created to illustrate how the project has progressed over time. Data on the project history is provided by the [Status.get_analytics() function](https://github.com/CoLRev-Ecosystem/colrev/blob/main/colrev/ops/status.py).

**Expected Effort Required**

2 months, 5 people.

**Comment by DjogoF** [comment]
Hallo @geritwagner , 
bezüglich das WI Projekt interessiert mich als 1. Wahl dieses Thema. So ich freue mich schon darauf mit andere arbeiten, zu können, die auch daran interessiert sind. 
Viele Grüße
Francine Djogo

**Comment by ossendorfluca** [comment]
Ich würde gerne an diesem Problem arbeiten.

**Comment by einfachjessi** [comment]
Hallo, ich würde gerne an der Bearbeitung dieses Issues teilnehmen.

**Comment by katharinaernst** [comment]
Hallo, ich würde auch gerne an diesem Issue arbeiten.

**Comment by Janus678** [comment]
Hallo, ich bin auch hier interessiert Option 2 für mich

**Comment by mhlbrsimon** [comment]
Hallo, im Rahmen des WI-Projekts würde ich am liebsten an diesem Projekt arbeiten.

**Comment by DjogoF** [comment]
Hallo Leute @einfachjessi @ossendorfluca @mhlbrsimon, 
ich habe die letzten beiden Kurse nicht besucht und würde gerne wissen, wie ihr euch organisiert habt.  Damit ich weiter mit euch an dem Code arbeiten kann, um ein offizielles Mitglied der Gruppe zu sein.
Meine E-Mail Adresse ist: francine.djogo-kenbou@stud.uni-bamberg.de
Danke für eure Rückmeldung
Djogo

**Comment by ossendorfluca** [comment]
Hallo @geritwagner, hier ist der Link zu unserer Fork: https://github.com/ossendorfluca/colrev

**Comment by geritwagner** [comment]
Danke! Wenn die Issue-Funktionalität für Ihre Arbeit hilfreich ist, können Sie diese auch im Fork aktivieren (siehe [link](https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig)).
