### ISSUE TITLE
feat: Unpaywall SearchSource

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#244]
**Description**

To enhance the CoLRev environment's capabilities, the search operation for Unpaywall should be implemented, leveraging its [REST API](https://unpaywall.org/products/simple-query-tool) to fetch search results effectively. This addition aims to broaden the sources from which CoLRev can retrieve and manage open-access research papers.

**Preferred Solution**

- **Implement a New SearchSource for Unpaywall:** Develop a SearchSource that interacts with Unpaywall's REST API, incorporating the use of page parameters for extensive searches. This SearchSource will enable users to query and retrieve search results directly from Unpaywall.

**Implementation Notes**

- Ensure the implementation respects API rate limits and adheres to Unpaywall's usage policies.
- Consider implementing efficient handling of page parameters to navigate through search results effectively.
- Similar to existing SearchSources, provide clear documentation on how users can specify their search queries.

**User Story**

1. Users initiate their CoLRev environment with `colrev init`.
2. They then use the command `colrev search -a colrev.unpaywall` to start a search operation, providing search terms as arguments or via a configuration file.
3. The CoLRev environment processes these terms, queries the Unpaywall API, and retrieves relevant search results.
4. These results are subsequently formatted and saved in a designated output file or database for further analysis or processing.
5. Users can perform repeated searches with new queries, and the system will update the stored search results accordingly, maintaining a comprehensive record of accessed documents.

**Expected Effort**

- **Estimated Duration:** 2 months
- **Team Composition:** 2-3 individuals

**Comment by annaglr** [comment]
I would also like to contribute to this issue

**Comment by tobiaspffl** [comment]
I would also like to contribute to this issue

**Comment by JohannesDiel** [comment]
I would like to contribute to this issue

**Comment by geritwagner** [comment]
Ok - we have group of 3 for the GitHub SearchSource :+1:  @0xmtyset , @annaglr and @tobiaspffl : can you select a group lead, fork the repository and link your repository in this feed?

**Comment by 0xmtyset** [comment]
The group has selected me as the group leader. Attached is the link to the forked repository: https://github.com/0xmtyset/colrev
