### ISSUE TITLE
feat: Springer SearchSource

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#245]
**Description**

Enhance the existing framework for Springer SearchSource in CoLRev to fully support detailed search and retrieval, including authentication with personal tokens.

**Preferred Solution**

- **Complete `search` Method:** Implement the detailed functionality for searching Springer's database.
- **Support for Authentication:** Enable use of personal tokens for accessing [Springer's API](https://dev.springernature.com/).

**User Story**

1. Upon initiating CoLRev with `colrev init`, a user sets up their environment for Springer searches.
2. The user runs `colrev search -a colrev.springer`, entering their search parameters and personal token for authentication.
3. CoLRev authenticates with Springer's API using the provided token and sends the search query.
4. Search results are retrieved from Springer and stored in a designated file or database within the user's CoLRev environment.
5. Users can perform additional searches with different parameters, with each set of results being added to their cumulative search data.

**Implementation Notes**

- Carefully implement authentication to ensure security and privacy of user tokens.
- Review and adhere to Springer's API documentation for query structures and authentication protocols.
- Use and extend the existing CoLRev package for Springer.

**Expected Effort**

- **Estimated Time:** 2 months
- **Team Members Required:** 2-3

**Comment by Peteer98** [comment]
I want to work on this issue (2)

**Comment by LouisLangenhan** [comment]
I would like to contribute to that issue (2nd choice)

**Comment by CelinaSchwarz** [comment]
I would like to contribute to that issue

**Comment by QuynhMaiNguyen** [comment]
I would like to contribute to that issue

**Comment by Bnati** [comment]
I would like to contribute to that issue

**Comment by pmao0907** [comment]
I would like to work on this issue. :)

**Comment by omanovb** [comment]
I would like to contribute to thas issue

**Comment by MingxinJiang** [comment]
I would like to work on this issue

**Comment by geritwagner** [comment]
We currently have more people interested in this topic than expected. One option would be to extend the requirements a bit to ensure that there is enough work for a team of five. Please let me know whether I should make a suggestion or whether you prefer to split the group.

**Comment by Bakuu97** [comment]
I would like to contribute to that issue as my third choice

**Comment by pmao0907** [comment]
I can switch to topic OSF

**Comment by MingxinJiang** [comment]
> We currently have more people interested in this topic than expected. One option would be to extend the requirements a bit to ensure that there is enough work for a team of five. Please let me know whether I should make a suggestion or whether you prefer to split the group.

I can also switch to topic OSF

**Comment by geritwagner** [comment]
Thank you, @pmao0907  and @MingxinJiang  for offering to switch to #360 . This leaves a group of 3 with @CelinaSchwarz , @omanovb and @QuynhMaiNguyen  :+1: Can you select a group lead, fork the repository and link your repository in this feed?
