### ISSUE TITLE
feat: SemanticScholar as a SearchSource

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#247]
# Feature Request

**Describe the Feature Request**

For [SemanticScholar](https://www.semanticscholar.org/), the search operation should be supported.

**Describe Preferred Solution**

SemanticScholar provides access to a large database of academic papers. It can be accessed through an [API](https://www.semanticscholar.org/product/api) with an unofficial [Python client](https://github.com/danielnsilva/semanticscholar). The [crossref](https://github.com/CoLRev-Environment/colrev/blob/main/colrev/ops/built_in/search_sources/crossref.py) SearchSource could be taken as an inspiration to implement a SearchSource for SemanticScholar. As an extension, token-based authentication should be supported ([1](https://www.semanticscholar.org/product/api#api-key)). To store private keys, the [IEEE](https://github.com/CoLRev-Environment/colrev/blob/main/colrev/ops/built_in/search_sources/ieee.py) SearchSource provides and example.

To consolidate the codebase, code implemented for the [SemanticScholar prep package](https://github.com/CoLRev-Environment/colrev/blob/main/colrev/ops/built_in/prep/semantic_scholar_prep.py) should be migrated to the new SearchSource.

**Expected Effort Required**

2 months, 3-4 people.

**Comment by Peteer98** [comment]
I want to work on this issue (1)

**Comment by LuminousLynx** [comment]
This issue would be my 1st choice to work on.

**Comment by user123projekt** [comment]
SemanticScholar as a SearchSource

**Comment by geritwagner** [comment]
Closed by #288
