### ISSUE TITLE
feat: OSF SearchSource

### ISSUE THREAD

**Issue by geritwagner** [CoLRev-Environment/colrev#360]
**Description**

Currently, the Open Science Framework (OSF) is not available as a SearchSource within the CoLRev environment. This feature request aims to develop and integrate OSF as a new SearchSource, enabling users to search and retrieve data from OSF projects directly through CoLRev, with an emphasis on supporting authentication for access.

**Preferred Solution**

Create a new SearchSource for OSF that:

- Implements the `search` method to query the OSF API for projects based on specified search criteria (e.g., title, tags, contributors).
- Supports token-based authentication to access the OSF API, following the example set by the IEEE SearchSource implementation. This will allow users to perform authenticated searches and access private or restricted projects where permissions are granted.

**User Story**

1. **Initialize CoLRev:** A user begins by initializing a new CoLRev project with the command `colrev init`, setting up the environment for integrating with OSF.
2. **Add OSF SearchSource:** The user adds OSF as a search source using the command `colrev add -a colrev.osf`, which prompts them to enter necessary search parameters and authentication details for the OSF API.
3. **Execute Search:** With the search source and parameters configured, the user runs the search using `colrev search`, which utilizes the entered API token for authenticated access to the OSF API and returns relevant project data.
4. **Process and Store Results:** The retrieved data, including detailed project metadata and resources, is processed and made available for further actions within CoLRev, such as analysis or reporting.

**Links for Reference and Development**

- [OSF API Documentation](https://developer.osf.io/) - Essential for understanding how to interact with the OSF API, including authentication and data retrieval.
- [IEEE Package for Token Authentication Example](https://github.com/CoLRev-Environment/colrev/blob/main/colrev/packages/ieee/src/ieee.py) - To reference the implementation of token-based authentication.

**Expected Effort**

- **Duration:** 2 months
- **Team Requirement:** 3-4 individuals

**Comment by MingxinJiang** [comment]
I would like to work on this issue

**Comment by MingxinJiang** [comment]
> I would like to work on this issue

as second choice

**Comment by Bakuu97** [comment]
I would like to contribute to that issue as my second choice

**Comment by JohannesDiel** [comment]
I would like to contribute to that issue as my second choice

**Comment by ArdaTasdelen** [comment]
I want to contribute to this issue as my second choice

**Comment by ciremcelen** [comment]
I want to contribute to this issue as my second choice

**Comment by geritwagner** [comment]
We should have a group of 3 here: @pmao0907 , @MingxinJiang  and @JohannesDiel (?) Does that work for you?

**Comment by geritwagner** [comment]
Thank you, @JohannesDiel for joining this issue. Please go ahead, select a group lead, fork the repository and link your repository in this feed :+1:

**Comment by pmao0907** [comment]
Link to repository: https://github.com/pmao0907/colrev    
@MingxinJiang @JohannesDiel
