### ISSUE TITLE
dev: reduce the amout of automatically generated directories named "colrev"

### ISSUE THREAD

**Issue by dengdenglele** [CoLRev-Environment/colrev#424]
After installation of CoLRev according to the readthedocs manual, there are three different directories named "colrev"

- in the $HOME directory of the current user. This $HOME/colrev/ directory seems to function as a temp directory. It contains the following:
    - two hidden directories: ".colrev_temp" and ".tei_index"
    - one .sqlite file: "prep_requests_cache.sqlite"
    - one .json file: "registry.json"
    - the .sqlite and .json file might be specific to my setup. The two hidden directories will always be created
    - possible solution: change this directory into a hidden one e.g. $HOME/.colrev/

- on the Desktop (default installation path according to readthedocs instructions) is a colrev directory within colrev. $HOME/Desktop/colrev/colrev
    - the first colrev directory is created due to git clone (automatically) onto the Desktop 
    - suggestion: change the nested colrev directory into src or something similar
    - current: $HOME/Desktop/colrev/colrev/
    - possible solution: $HOME/Desktop/colrev/src/

**Comment by geritwagner** [comment]
I renamed the $HOME/colrev/  directory to $HOME/.colrev/, as suggested. Concerning the colrev package, I suggest that the modules remain in a colrev subdirectory (instead of a src directory). This is consistent with established packages like pandas, numpy, and scipy.
